export const projects = [
    {
        title: "Handmade E-Commerce Website",
        description: "Full-stack platform connecting customers and vendors for handcrafted products. Features include real-time admin control and vendor management.",
        tags: ["React", "Firebase", "Context API", "Tailwind"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_500,h_400,c_fill,f_auto,q_auto/v1776034103/p10_afzqqv.png",
        source_code_link: "https://github.com/mahmoudhussein6/HandMade_Website_GraduationProject",
        live_link: "https://hand-made-website-graduation-projec-seven.vercel.app/",
    },
    {
        title: "Smart Assistant Glasses (SAG)",
        description: "Accessibility-focused system with website & dashboard for product orders and analytics. Built with Angular, TS, and Bootstrap.",
        tags: ["Angular", "TypeScript", "Bootstrap"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_500,h_400,c_fill,f_auto,q_auto/v1776033208/Smart_drkjt1.png",
        source_code_link: "https://github.com/mahmoudhussein6/SmartAssistantGlassesCode",
        live_link: "https://www.linkedin.com/posts/mahmoud-hussein-0bb055242_sag-smartassistantglasses-aiforaccessibility-activity-7085287650022035457-ZIgo?utm_source=share&utm_medium=member_desktop&rcm=ACoAADwp108BQ3qGUZG-G2cUIIkoBXGE6x2CfFc",
    },
    {
        title: "Terllo | Workspace OS",
        description: "Premium, high-performance project management application inspired by Trello, designed for modern, intelligence-driven teams.",
        tags: ["React", "Zustand", "GSAP", "Tailwind"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_600,h_400,c_fill,f_auto,q_auto/v1776033218/terllo_jlvwou.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/terllo-clone",
        live_link: "https://terllo-clone-six.vercel.app/#/dashboard",
    },
    {
        title: "Echo System",
        description: "An online marketing company in Beni Suef, we help you grow and reach more customers through photography, design, paid advertising.",
        tags: ["React", "Tailwind", "JavaScript", "Framer Motion"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_400,h_400,c_fill,f_auto,q_auto/v1776033001/echo_vq4ovb.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/echoSystem",
        live_link: "https://echo-system-gamma.vercel.app/",
    },
    {
        title: "Fresh Cart",
        description: "E-commerce website using React, TailwindCSS, and JWT Auth. Integrated React Query for caching and Context API.",
        tags: ["React", "TailwindCSS", "React Query", "JWT"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_500,h_400,c_fill,f_auto,q_auto/v1776033319/Fresh_dnuu1h.png",
        source_code_link: "https://github.com/mahmoudhussein6/FreshCart",
        live_link: "https://www.linkedin.com/posts/mahmoud-hussein-0bb055242_react-webdevelopment-tailwindcss-activity-7253044158003638272-4jW6/?utm_source=share&utm_medium=member_desktop&rcm=ACoAADwp108BQ3qGUZG-G2cUIIkoBXGE6x2CfFc",
    },
    {
        title: "Vanilla JS E-Commerce",
        description: "Built with HTML, CSS, and JavaScript featuring separate Admin/User roles, API integration, and persistent cart.",
        tags: ["JavaScript", "HTML5", "CSS3", "API"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_500,h_400,c_fill,f_auto,q_auto/v1776033373/Costco_ehayzn.png",
        source_code_link: "https://github.com/mahmoudhussein6/E-commerce_Appliction",
        live_link: "https://e-commerce-appliction-six.vercel.app/index.html",
    },
    {
        title: "Veterinary Pharmacy Management System",
        description: "Professional inventory management system designed specifically for veterinary pharmacies, aimed at tracking products.",
        tags: ["React", "Tailwind", "Firebase"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_500,h_400,c_fill,f_auto,q_auto/v1776033320/vet_ll7gct.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/Veterinary_Pharmacy_Management_System",
        live_link: "https://veterinary-pharmacy-management-syst.vercel.app/",
    },
    {
        title: "Portfolio Website",
        description: "A modern, responsive, and interactive portfolio website built with React, Tailwind CSS, Framer Motion, and Anime.js.",
        tags: ["React", "TailwindCSS", "GSAP", "React Hook Form", "ZOD"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_500,h_400,c_fill,f_auto,q_auto/v1776096471/portfoilio_fkwaxi.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/My_Portfolio",
        live_link: "https://my-portfolio-phi-virid-40.vercel.app/",
    },
    {
        title: "Ramadan Challenge Tracker",
        description: "A beautiful, responsive web application to track spiritual progress during Ramadan. Built with React and Tailwind CSS.",
        tags: ["React", "TailwindCSS", "Framer Motion"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_400,h_400,c_fill,f_auto,q_auto/v1776033200/ramdan_szdlky.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/RamadanPlan",
        live_link: "https://ramadan-plan.vercel.app/",
    },
    {
        title: "ProCV Builder",
        description: "High-performance, responsive web application built with React, allowing real-time resume creation and PDF export.",
        tags: ["React", "GSAP", "html2canvas", "jspdf"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_400,h_400,c_fill,f_auto,q_auto/v1776033031/cv_rstxnq.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/CV_Builder",
        live_link: "https://cv-builder-kappa-six.vercel.app/",
    },
    {
        title: "Khatwa - Your First Step",
        description: "Khatwa is a comprehensive platform designed to bridge the gap between ambitious individuals and their dreams in Spain. , Khatwa provides expert guidance and legal support.",
        tags: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "React Helmet Async"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033054/khatwa_qn74zg.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/Khatwa",
        live_link: "https://www.khatwa.es/",
    },
    {
        title: "MovicEg",
        description: "This website is a modern, responsive platform designed to showcase a wide range of fire safety and HVAC products. It allows users to explore products.",
        tags: ["React", "JavaScript", "TailwindCSS", "Framer Motion", "EmailJS"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033135/movicEg_zwc8x8.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/movicApp",
        live_link: "https://movic-app.vercel.app/",
    },
    {
        title: "Task Flow - To-Do App",
        description: "Task Flow is a high-performance, aesthetically pleasing to-do list application,It features a modern glassmorphic UI, smooth transitions, and persistent data storage.",
        tags: ["React", "JavaScript", "TailwindCSS", "Framer Motion", "localStorage"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033211/todolist_qhwkhs.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/to_do_list",
        live_link: "https://to-do-list-nu-two-20.vercel.app/",
    },
    {
        title: "Weather App",
        description: "Weather App is a responsive web application that displays the current weather conditions for a specified location.",
        tags: ["React", "JavaScript", "TailwindCSS", "Framer Motion", "Weather API"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033325/Weather_lzakzb.png",
        source_code_link: "https://github.com/mahmoudhussein6/WeatherAppReact",
        live_link: "https://weather-app-react-bay-eta.vercel.app/",
    },
    {
        title: "Movies App",
        description: "Movies App is a responsive web application that displays the current movies information for a specified location.",
        tags: ["Angular", "TypeScript", "TailwindCSS", "TMDB API", "RxJS"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_400,h_300,c_fill,f_auto,q_auto/v1776034059/Movie_uemkyf.png",
        source_code_link: "https://github.com/mahmoudhussein6/Movie_Application",
        live_link: "https://movie-application-cbut.vercel.app/movies",
    },
    {
        title: "Note Taking App",
        description: "Note Taking App (React) A clean and efficient Note Taking Application built with React, allowing users to create, update, and delete notes with a modern and responsive user interface.",
        tags: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "localStorage"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033229/bg_fk55fd.png",
        source_code_link: "https://github.com/mahmoudhussein6/NoteApplicationReact",
        live_link: "https://note-application-react.vercel.app/",
    },
    {
        title: "تطبيق اذكر الله",
        description: "تطبيق إلكتروني عصري للأذكار والتسبيح، مصمم بلمسات جمالية متميزة وتجربة مستخدم سلسة. يهدف التطبيق إلى مساعدتك في الحفاظ على أورادك اليومية بكل سهولة.",
        tags: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "React Icons"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033012/dhaker_hz0tqz.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/Dhaker-App",
        live_link: "https://dhaker-app.vercel.app/",
    },
    {
        title: "موقع مواقيت الصلاة",
        description: "موقع ويب عصري، جذاب، واحترافي لعرض مواقيت الصلاة بدقة عالية، مصمم خصيصاً بتجربة مستخدم مميزة وتصميم فريد.",
        tags: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "React Hook Form", "Axios", "Aladhan API"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033187/prayer_toyfvd.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/prayer-times",
        live_link: "https://prayer-times-blond.vercel.app/",
    },
    {
        title: "القرآن الكريم",
        description: "تجربة قرآنية رقمية فاخرة، تجمع بين جمال التصميم وسهولة الاستخدام.",
        tags: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "Axios", "mp3quran.net API", "alquran.cloud API"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033193/quran_pl0td6.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/Quran-App",
        live_link: "https://quran-app-olive.vercel.app/",
    },
    {
        title: "Expense Tracker",
        description: "A Modern and responsive Expense Tracker application built with React, designed to help users manage their personal finances by tracking income and expenses easily and efficiently.",
        tags: ["React", "TypeScript", "TailwindCSS", "Context API", "localStorage", "React Icons"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776033055/expense_vkjzoo.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/Expense_Tracker",
        live_link: "https://expense-tracker-gamma-vert-12.vercel.app/",
    },
    {
        title: "Admin Dashboard - Manager Pro",
        description: "A modern, responsive admin dashboard built with Angular 21, featuring NgRx state management, interactive charts, and a clean Material Design-inspired UI.",
        tags: ["Angular", "TypeScript", "Material UI", "NgRx", "RxJS", "Chart.js", "SCSS"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_500,h_400,c_fill,f_auto,q_auto/v1776033225/adminDash_tuvofi.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/Admin_Dashboard",
        live_link: "https://admin-dashboard-woad-eight-46.vercel.app/dashboard",
    },
    {
        title: "Mini E-Commerce Application",
        description: "Build a responsive mini e-commerce frontend using Vite + React.js, showcasing your understanding of modern React practices.",
        tags: ["React", "TypeScript", "TailwindCSS", "Framer Motion", "Axios", "React Router", "Fake Store API", "React Hook Form", "ZOD"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_400,h_400,c_fill,f_auto,q_auto/v1776033223/store_qgknmz.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/E-commerce_Appliction_React",
        live_link: "https://e-commerce-appliction-react.vercel.app/",
    },
    {
        title: "Questions & Answers For React",
        description: "Questions & Answers For React is a responsive web application that displays the current questions and answers.",
        tags: ["React", "TypeScript", "TailwindCSS", "Framer Motion"],
        image: "https://res.cloudinary.com/dojghbhxq/image/upload/w_300,h_400,c_fill,f_auto,q_auto/v1776034071/question_f1vwg4.jpg",
        source_code_link: "https://github.com/mahmoudhussein6/Question_For_React_V1",
        live_link: "https://question-for-react-v1-27lx.vercel.app/",
    },
];
